site_name: Telecom Craft Home Labs
site_url: https://labs.telecomcraft.com
repo_url: https://github.com/telecomcraft/homelabs
repo_name: telecomcraft/homelabs

theme:
  name: material
  logo: assets/logo.svg
  icon:
    repo: fontawesome/brands/github
  palette:
    # - primary: "grey"
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to Light Mode
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.path
    - search.highlight
    - content.code.copy

copyright: >
  All content licensed under the <a href="http://creativecommons.org/licenses/by/4.0/">Creative Commons</a> by Telecom Craft – <a href="#__consent">Change cookie settings</a>

extra:
  social:
    - icon: fontawesome/brands/youtube 
      link: https://www.youtube.com/@telecomcraft
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/telecomcraft
    - icon: fontawesome/brands/github
      link: https://github.com/telecomcraft
    - icon: fontawesome/brands/twitter
      link: https://www.twitter.com/thetelecomcraft
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
    - Home: 'index.md'
    - About: 'about.md'
    - Blog:
      - blog/index.md
    #- Fiber Labs:
    #  - Fiber Labs Overview: 'labs/fiber/overview.md'
    - Network Labs:
      - Network Labs Overview: 'labs/networks/overview.md'
      - General Labs:
        - Creating a Network Host Template in Proxmox: 'labs/networks/general/creating-a-network-host-template-in-proxmox.md'
        - Cloning a Network Host Template in Proxmox: 'labs/networks/general/cloning-a-network-host-template-in-proxmox.md'
        - Connecting and Configuring Network Hosts in Proxmox: 'labs/networks/general/connecting-and-configuring-network-hosts-in-proxmox.md'
      - Juniper Labs:
        - Installing Juniper vSRX on Proxmox: 'labs/networks/juniper/installing-vsrx-on-proxmox.md'
        #- Initial Junos OS Configuration: 'labs/networks/juniper/initial-junos-os-configuration.md'
      #- VyOS Labs:
        #- Installing VyOS on Proxmox: 'labs/networks/vyos/installing-vyos-on-proxmox.md'
    #- Server Labs:
    #  - Server Labs Overview: 'labs/servers/overview.md'
    #- Security Labs:
    #  - Security Labs Overview: 'labs/security/overview.md'
    

plugins:
  - blog
  - search
  - git-committers:
      repository: telecomcraft/homelabs
      branch: main
  - git-revision-date-localized:
      enable_creation_date: true
  - tags:
      tags_slugify: !!python/object/apply:pymdownx.slugs.slugify
          kwds:
            case: lower
      tags_file: tags.md